apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: p1lylkin2/hw
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: PGHOST
          value: "postgres-service"  # имя сервиса базы данных
        - name: PGUSER
          value: "todo_user"
        - name: PGPASSWORD
          value: "todo_password"
        - name: PGDATABASE
          value: "todo_db"
